### ISSUE TITLE
Error about modifying the input shape

### ISSUE THREAD

**Issue by weiyuchens** [antonior92/automatic-ecg-diagnosis#14]
The model requires us to input data with shape = (N, 4096, 12), but because my training set is data with a sampling rate of 500HZ and a recording duration of 10 seconds. So I wish to modify the input shape=(N, 5000, 12).

I updated the code in the `model.py` as follows:

``
    # signal = Input(shape=(4096, 12), dtype=np.float32, name='signal')
``

``
    signal = Input(shape=(5000, 12), dtype=np.float32, name='signal')
``

but it caused some problems, the errors content of the question is as follows:

```
2021-12-09 14:51:34.523544: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-12-09 14:51:34.523562: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-09 14:51:34.523576: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nmslab-004118.nms.kcl.ac.uk): /proc/driver/nvidia/version does not exist
2021-12-09 14:51:34.523874: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-12-09 14:51:34.663666: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3600000000 Hz
2021-12-09 14:51:34.664192: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7efcb4000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-12-09 14:51:34.664222: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-12-09 14:51:35.462783: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
Epoch 1/70
2021-12-09 14:51:43.805704: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
 1/25 [>.............................] - ETA: 0s - loss: 0.80672021-12-09 14:51:48.490054: I tensorflow/core/profiler/rpc/client/save_profile.cc:168] Creating directory: ./logs/train/plugins/profile/2021_12_09_14_51_48
2021-12-09 14:51:48.504534: I tensorflow/core/profiler/rpc/client/save_profile.cc:174] Dumped gzipped tool data for trace.json.gz to ./logs/train/plugins/profile/2021_12_09_14_51_48/nmslab-004118.nms.kcl.ac.uk.trace.json.gz
2021-12-09 14:51:48.544836: I tensorflow/core/profiler/utils/event_span.cc:288] Generation of step-events took 0.323 ms

2021-12-09 14:51:48.572273: I tensorflow/python/profiler/internal/profiler_wrapper.cc:87] Creating directory: ./logs/train/plugins/profile/2021_12_09_14_51_48Dumped tool data for overview_page.pb to ./logs/train/plugins/profile/2021_12_09_14_51_48/nmslab-004118.nms.kcl.ac.uk.overview_page.pb
Dumped tool data for input_pipeline.pb to ./logs/train/plugins/profile/2021_12_09_14_51_48/nmslab-004118.nms.kcl.ac.uk.input_pipeline.pb
Dumped tool data for tensorflow_stats.pb to ./logs/train/plugins/profile/2021_12_09_14_51_48/nmslab-004118.nms.kcl.ac.uk.tensorflow_stats.pb
Dumped tool data for kernel_stats.pb to ./logs/train/plugins/profile/2021_12_09_14_51_48/nmslab-004118.nms.kcl.ac.uk.kernel_stats.pb
25/25 [==============================] - ETA: 0s - loss: 0.8029Traceback (most recent call last):
  File "train.py", line 60, in <module>
    history = model.fit(train_seq,
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 862, in fit
    val_logs = self.evaluate(
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1081, in evaluate
    tmp_logs = test_function(iterator)
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 650, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1661, in _filtered_call
    return self._call_flat(
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/home/k20020475/PycharmProjects/auto_ecg_dnn/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [31,1] vs. [32,1]
         [[node binary_crossentropy/logistic_loss/mul (defined at train.py:60) ]] [Op:__inference_test_function_5585]

Function call stack:
test_function
```

How can I solve this problem?

**Comment by antonior92** [comment]
Hi Weiyu,

Thank you for your interest in our work. The problem of changing the Input dimension is that you would need to change the dimension of the intermediary layers as well... And 4096 is quite a convenient number because it is a power of 2. Hence it makes it quite easy to get the dimensions right in the intermediate layers after pooling layers...

My suggestion would be to downsample your signal to 400 Hz so your 10-second signal would be equivalent to 4000 samples and you can add zeros on each side of the signal (so the signal is 4096 samples). You can use scipy.signal.resample_poly todo the resampling.

**Comment by antonior92** [comment]
see also issue #3
